// Re-export from modular structure for backward compatibility
export {
  API_CONFIG,
  API_ENDPOINTS,
  HTTP_STATUS,
  ERROR_MESSAGES,
  AUTH_ENDPOINTS,
  WORKSPACE_ENDPOINTS,
  PROJECT_ENDPOINTS,
  TASK_ENDPOINTS,
  CHAT_ENDPOINTS,
  NOTIFICATION_ENDPOINTS,
  FILE_ENDPOINTS,
} from "./apiConfigModule";
